name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Grant executable permissions to mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Grant executable permissions to mvnw
        run: chmod +x mvnw

      - name: Run tests with Maven
        run: ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Destroy Previous Infrastructure
        working-directory: terraform
        run: terraform destroy --auto-approve

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply --auto-approve